### ISSUE TITLE
Frontend character encoding issues

### ISSUE THREAD

**Issue by jpjenk** [paleobiodb/classic#7]
We still have problems displaying some non-standard characters. See Lagerstätten

**Comment by jpjenk** [comment]
All non-ASCII character display issues resolved with an extensive code refactoring which included collecting all print statements from and returning them all as a concatenated string to Dancer.

**Comment by markuhen** [comment]
Looks like we still have a problem with this. See the attachment below. That should be Solé and we are getting a strange character in place of the accented e.

![sole](https://cloud.githubusercontent.com/assets/19557452/23914069/3bfd6500-08bb-11e7-85bf-925a06197116.jpeg)

**Comment by evlacho** [comment]
Good to see that this issue has been pointed out. The same happens when data are downloaded from the PBDB. The csv file contains all these strange characters, which is really annoying for the user. I personally stopped entering accented or special characters in the PBDB

**Comment by mmcclenn** [comment]
The new dockerized version of the PBDB works perfectly with accented characters. Please do start entering them again.
